import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { Inter, Oswald} from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})


const oswald = Oswald({
    subsets: ['latin'],
    display: 'swap',  
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <header className="bg-dark-header w-full h-16 flex items-center justify-center shadow-xl fixed">
          <div className="container mx-auto w-full flex gap-8">
            <Image src="https://cdn.discordapp.com/attachments/1100524910733963266/1281674196342018131/image.png?ex=66dc939c&is=66db421c&hm=ac37da77a47e29b0939bafcc4ef10ef6a08b3c1a93ef04e6b67518273563254b&" width={90} height={90} alt=""/>
            <ul className="flex gap-12 items-center text-white">
              <li><Link href="#">Home</Link></li>
              <li><Link href="#">Bestiário</Link></li>
              <li><Link href="#">Sobre nós</Link></li>
              <li><Link href="#">Parceiros</Link></li>
            </ul>
          </div> 
        </header>
        {children}
      </body>
    </html>
  );
}
